// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// generalized_logistic
NumericVector generalized_logistic(double r_max, double K, double N1, double z, double num_years, NumericVector catch_series);
RcppExport SEXP _HumpbackSIR_generalized_logistic(SEXP r_maxSEXP, SEXP KSEXP, SEXP N1SEXP, SEXP zSEXP, SEXP num_yearsSEXP, SEXP catch_seriesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type r_max(r_maxSEXP);
    Rcpp::traits::input_parameter< double >::type K(KSEXP);
    Rcpp::traits::input_parameter< double >::type N1(N1SEXP);
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type num_years(num_yearsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type catch_series(catch_seriesSEXP);
    rcpp_result_gen = Rcpp::wrap(generalized_logistic(r_max, K, N1, z, num_years, catch_series));
    return rcpp_result_gen;
END_RCPP
}
// dlnorm_zerb
NumericVector dlnorm_zerb(NumericVector x, NumericVector meanlog, NumericVector sdlog, bool return_log);
RcppExport SEXP _HumpbackSIR_dlnorm_zerb(SEXP xSEXP, SEXP meanlogSEXP, SEXP sdlogSEXP, SEXP return_logSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type meanlog(meanlogSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sdlog(sdlogSEXP);
    Rcpp::traits::input_parameter< bool >::type return_log(return_logSEXP);
    rcpp_result_gen = Rcpp::wrap(dlnorm_zerb(x, meanlog, sdlog, return_log));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HumpbackSIR_generalized_logistic", (DL_FUNC) &_HumpbackSIR_generalized_logistic, 6},
    {"_HumpbackSIR_dlnorm_zerb", (DL_FUNC) &_HumpbackSIR_dlnorm_zerb, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_HumpbackSIR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
